### PR TITLE
Rook valid move

### PR DESCRIPTION
**Pull request by cldambrosio**

### CODE REVIEW

**Comment by hereismyusername** [comment]
I think the codacy suggestion makes sense.

**Comment by cldambrosio** [comment]
Which suggestion in particular?
I committed changes to comply to Codacy's style guide.
I'm not sure I should change the code as suggested however because we haven't adopted Codacy's guidelines so far. We discussed whether we should use `self` or not given that it is functionally the same and agreed that personal preference was ok for now?
Regarding the use of `unless` over `if` I find the line 
`return false unless super(new_file, new_rank)` to be somewhat less readable than 
`return false if !super(new_file, new_rank)` in this case. That's personal though; happy to change this if you prefer!

**Comment by hereismyusername** [comment]
I meant the "unless" suggestion. 

But it's fine with me if you prefer "if". 

I used "if" for the bishop, but noticed "unless" being used elsewhere.

**Comment by cldambrosio** [comment]
Does style inconsistency count as technical debt? :sweat_smile:

**Pull request merged**
