### PR TITLE
add way to update games

### PR DESCRIPTION
**Pull request by hereismyusername**
"def game_params" method to be updated after database fields agreed on.

### CODE REVIEW

**Comment by hereismyusername** [comment]
Good question!

**Comment by RajSannidhi** [comment]
Looking at the create_games migration, I'm also wondering why the various player_ids are integers rather than strings... wouldn't they refer to usernames? ( @reneesandefur , you might have an answer.)

**Comment by hereismyusername** [comment]
Would the database assign a number to each player as they're created?

**Comment by RajSannidhi** [comment]
That makes sense. I guess a single number per user is easier to store and search through than a distinct string per user.

**Comment by reneesandefur** [comment]
With update I think we are referring to updating the database after each move which is why we have the move model. So, in that case we would need to redirect to the game path not the root path eventually if we are listing all games being played by the user on the index and maybe the game currently being played on a show page? Right now we only have the root path so I think it's ok.

With the id, think back to Flixter. The player id will correspond directly with that particular game and since the user/player will have many games that's how we'll use the database to associate the player with that particular game

**Comment by hereismyusername** [comment]
Please see new commit "Edit params".

**Pull request merged**
