### PR TITLE
Is obstructed method

### PR DESCRIPTION
**Pull request by cldambrosio**

### CODE REVIEW

**Comment by reneesandefur** [comment]
Oh I hadn't seen everything else you did prior to what I commented on earler

**Comment by garyravago** [comment]
Claire, I've taken a look at your code and the tests you wrote seem to pass which is excellent!  I even tested it in the rails console by moving the current_square and obstruction pieces around to various spots.

The only thing I'm concerned with is the order of the rank and file arguments.  It didn't seem very intuitive at first because I was running with the assumption that the arguments would be structured **(file,rank)** so that it mimics the translation from chess notation as well the x,y coordinate system we're familiar with.

chess_notation

For example, e4 translates to (5,4)    (_assuming that file e = 5_)

So in your horizontal obstruction test to the right...

`    before(:each) do
      @game = FactoryGirl.build(:game)
      @current_square = FactoryGirl.create(:piece, rank: 4, file: 4, game: @game)    
    end`


`   it "checks if there is an obstruction horizontally to the right" do
      obstruction = FactoryGirl.create(:piece, rank: 4, file: 5, game: @game)
      expect(@current_square.is_obstructed?(4, 6)).to be true
    end
`



This is how it appeared to me.  I created this coordinate grid to help me translate the chess board better:
chessboard_file_rank

You can probably see how I got confused since I was thinking in terms of how naturally the first arg is an x (the file column) and the second is a y coordinate (the rank rows).

I had to re-create this coordinate grid to match how it would appear on your tests like so:

chessboard_rank_file


For me, it didn't seem intuitive since I'm so used to seeing a coordinate grid system structured (x,y) rather than (y,x).


I believe it would be easier to have the is_obstructed? arguments flipped around so that it is ordered **(col,row)**.  Your tests would have to be remapped to match this different order which shouldn't be too difficult but you logic implementation wouldn't change at all.


Let me know what you think or should we keep it as is.  We can also discuss this in the team meeting. 

I'm confident your logic is spot on and it seems to be working great!

**Comment by garyravago** [comment]
One other note, if you compare the coordinate grid pictures with rank/file images on Google, it looks like my picture is incorrect but the file(a-h)  represents the columns of the boards which is on the x-axis (horizontally) while the ranks(1-8) are the rows on the y-axis(vertically). Hope that's not too confusing

**Comment by cldambrosio** [comment]
Hey Gary, thank you for taking the time to illustrate so clearly your concern. In the past I never had to deal with (x, y) axis and for some reason the way I structured it came naturally. This is very useful feedback to me as it's highly likely to come up on the path of a software engineer! I will restructure the solution with (col, row) instead of (row, col) and push the code today.

**Comment by cldambrosio** [comment]
I pushed the refactored version for your review.

**Comment by garyravago** [comment]
Tested it out and it works great!  I'll bring up the grid picture today in the meeting to make sure we're all on the same page with how we're seeing the chessboard.

I'll go ahead and merge your pull request in

**Pull request merged**
