### PR TITLE
Websocket

### PR DESCRIPTION
**Pull request by cldambrosio**
Real-time screen update when the opponent moves a piece :boom:

### CODE REVIEW

**Comment by RajSannidhi** [comment]
Hey Claire: I think we should avoid using "location.reload()" and triggering a full page refresh since we already have some partial HTML files and Javascript written explicitly to trigger partial page refreshes when a piece is moved. I can handle that for the turn display if you like, but I'm not sure how to go about doing that for this.

**Comment by cldambrosio** [comment]
Can we refactor this later? "Make it work, make it fast, make it good" as I was taught...

**Comment by RajSannidhi** [comment]
Hi Claire,

Sorry for the delay following up on this. Is there something in particular I need to do after I clone the branch to make this work? I ran bundle install, opened up two separate test accounts in Chrome (one in regular browser and one in incognito mode), started a game against myself and started moving pieces. The pieces I move in one aren't updating in the other until I refresh.

Off the cuff, my guess is that we either need to eliminate the need for full page refreshes as we discussed, or we need to find a way to refresh the window on both players' ends.

**Comment by cldambrosio** [comment]
Hey Raj, did you see my message on Slack a few days ago about this? Sorry I thought it may have been easier through direct messaging, I should have written instructions here:

You need to set up the secret credentials on your local environment to see the real-time feature work. These are not on the repo because I added the file to the `.gitignore`.
(I actually committed the file twice by mistake and had to re-issue secret keys with Pusher! Glad I make those mistakes while training :cold_sweat: :grimacing:)

I sent you a collaborator invite from Pusher. You should have received this on your gmail account some days ago? Once you've signed up and signed in; look for the app keys

pusher

 and add them in a `/config/application.yml` file like:
```
# Pusher credentials
APP_ID:      'our-app-id-here'
APP_KEY:     'our-key-here'
APP_SECRET:  'our-secret-here'
APP_CLUSTER: 'mt1'
```

Then with 2 localhost windows, showing the same game, you should see the real-time feature work. Feel free to DM me on Slack if you need any help. Cheers!

**Review by RajSannidhi — APPROVED** [review]

**Pull request merged**
