### PR TITLE
Added valid move method to queen model

### PR DESCRIPTION
**Pull request by RajSannidhi**
Created a valid queen move method by gently tweaking Renee's valid king move method.

### CODE REVIEW

**Comment by reneesandefur** [comment]
@RajSannidhi I moved the on the board logic to the piece method so you may want to update the queen model before we merge

**Comment by RajSannidhi** [comment]
Thanks for the heads up. It should be good now.

**Comment by RajSannidhi** [comment]
Oh yes, sorry! And don't worry, I appreciate the critical eye. I sort of assumed the method on the Piece class was going to be run separately rather than being called within this method but I should have checked instead of assuming. Thanks for letting me know.

**Comment by hereismyusername** [comment]
Will you be writing tests?

**Comment by RajSannidhi** [comment]
Yes, working on them as we speak.

**Comment by reneesandefur** [comment]
@RajSannidhi One thing I am going to be updating in my valid_move branch for king is the self.file and self.rank. I know that we had that conversation when I first submitted and it turns out the self is redundant. You may want to update that as well.  If you run rubocop app/models/queen.rb(so you don't get all our errors) it will show you what needs to be adjusted and that will be one of the things

**Comment by RajSannidhi** [comment]
These should be good now. (Cleared out some files with my mentor while trying to fix testing on my end, but he assures me they're not needed.)

**Pull request merged**
