### PR TITLE
Valid move pawn

### PR DESCRIPTION
**Pull request by reneesandefur**

### CODE REVIEW

**Comment by hereismyusername** [comment]
This is a complex piece!

I understand we will add 'en passant' later if we have time.

But would it make sense to include a diagonal move to capture an opponent at this point?

A very minor point: it might be worth adding a little more detail to the test descriptions to make it clear which ones test for conditions that relate only to the first move.

**Comment by reneesandefur** [comment]
@hereismyusername i had logic for the capture move but i will probably add it as a separate method bc rubocop was saying the #valid_move? method was too complex with it

**Comment by hereismyusername** [comment]
I see. I didn't realise, as I haven't been using rubocop.

**Comment by reneesandefur** [comment]
@hereismyusername i will add some more details to the comments as well!

**Pull request merged**
